name: E-DrawGuide Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH orqali ulanish va yangilash
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/e-drawguide
            git fetch --all
            git reset --hard origin/main
            sudo chmod -R 777 logs uploads || true
            docker-compose stop app || true
            docker-compose rm -f app || true
            docker-compose up --build -d app
            sleep 5
            docker-compose exec -T app npm run db:migrate
            docker system prune -f